config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
require 'action_view'

class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  CAT_COLORS = %w(black white orange brown)

  validates :birth_date, :name, :color, :sex, :description, presence: true
  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)

  has_many :rental_requests,
  foreign_key: :cat_id,
  class_name: "CatRentalRequest",
  dependent: :destroy

  def age
    time_ago_in_words(birth_date)
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS_STATES = %w(APPROVED PENDING DENIED)

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: STATUS_STATES

  belongs_to :cat

  after_initialize :assign_pending_status

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
        NOT( (start_date > :end_date) OR ( end_date < :start_date) )
      SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def does_not_overlap_approved_request
    return if self.denied?
    unless overlapping_approved_requests.empty?
      errors[:base] <<
        "Request conflicts with existing approve request"
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save!
      overlapping_pending_requests.update_all(status: "DENIED")
    end
  end

  def approved?
    self.status = "APPROVED"
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def denied?
    self.status = "DENIED"
  end

  def pending?
    self.status = "PENDING"
  end

  private
  def assign_pending_status
    self.status ||= "PENDING"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end


  private
  def cat_rental_request_params
    params
      .require(:cat_rental_request)
      .permit(:cat_id, :start_date, :end_date, :status)
  end

  def current_cat_rental_request
    @rental_request ||= CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attribute(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private
    def cat_params
      params.require(:cat).permit(:birth_date, :color, :sex, :name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_request/new.html.erb
<h1>Create rental request</h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat_rental_request_cat_id">Cat</label>
    <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
      <option></option>
      <% Cat.all.each do |cat| %>
      <option
      <%= @rental_request.cat_id == cat.id ? "selected" : "" %>
      <%= cat.name %>
      </option>
      <% end %>
    </select>
  <br>

  <label for="start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    id="start_date"
    value="<%= @rental_request.start_date %>">
  <br>

  <label for="end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    id="end_date"
    value="<% @rental_request.end_date %>">
  <br>

  <input type="submit">
</form>

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form  action="<% action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="name">Name</label>
  <input type="text" name="cat[name]" id="name" value="<%= cat.name %>">
  <br>

  <label for="sex">Sex</label>
  <input
    type="radio"
    name="cat[sex]"
    id="cat_sex_male"
    value="M"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">M</label>

  <input
    type="radio"
    name="cat[sex]"
    id="cat_sex_female"
    value="F"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">F</label>
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option></option>
    <% Cat::CAT_COLORS.each do |color| %>
    <option
      <%= cat.color == color ? "selected" : "" %>
      value="<%= color %>">
      <%= color.upcase %>
    </option>
    <% end %>
  </select>
  <br>

  <label for="birth_date">Birth Date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="birth_date"
    value="<%= cat.birth_date %>">
  <br>


  <label for="description">
    Description
    <textarea name="cat[description]" rows="10" cols="60">
    <%= cat.description %></textarea>
  </label>
  <br>

  <% submit_text = (cat.persisted? ? 'update' : 'create') + ' cat!' %>
  <input
    type="submit"
    value="<%= submit_text %>">

</form>

app/views/cats/edit.html.erb
<h1>Edit my cat</h1>

<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1>All cute cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_url(cat) %></li>
  <% end %>

  <%= link_to "Create cat", new_cat_url %>
</ul>

app/views/cats/new.html.erb
<h1>Your new cute cat!</h1>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table bgcolor="#FFFF00">
  <tr>
    <th>ATTRIBUTE</th>
    <th>VALUE</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
  <tr>
    <td><%= attr_name %></td>
    <td><%= @cat.send(attr_name) %></td>
  </tr>
  <% end %>
  <!-- <tr>
    <td>AGE<td>
    <td><%= @cat.age %>
  </tr>
  <tr>
    <td>BIRTH_DATE</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>COLOR</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>SEX</td>
    <td><%= @cat.sex %></td>
  </tr> -->

  <%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>

  <h2>Rental Requests</h2>
  <table>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
    </tr>
    <% @cat.rental_requests.order("start_date").each do |req| %>
    <tr>
      <td><%= req.start_date %></td>
      <td><%= req.end_date %></td>
      <td><%= req.status %></td>
    </tr>
    <% end %>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>